// mypages.js
// 2023-03-01: by jcr


exports.genMainPage = function(lista, data){
    var pagHTML = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
                </header>
        
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>`

    return pagHTML
}


exports.pessoasPage = function(lista, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
            </header>
            <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>
                        <a 
                        href="http://localhost:7777/pessoas">
                        Lista de pessoas
                        </a>
                    </th>
                    <th>
                        <a 
                        href="http://localhost:7777/sexo">
                        Distribuição por sexo
                        </a>
                    </th>
                    <th>
                    <a 
                        href="http://localhost:7777/desporto">
                        Distribuição por desporto
                        </a>
      
                    </th>
                    <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                </tr>    
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`

    for(let i=0; i < lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/${lista[i].id}">
                                ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}


exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>${pessoa.nome}</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>
    
        <div class="w3-container">
            `
    pagHTML += `
            
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}

exports.distribuicaoSexoPage = function(feminino, masculino,outro, data){
    
    var pagHTML = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>Distribuição por sexo </h1>
                </header>
                <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>
        
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Sexo</th>
                        <th>Número</th>
                    </tr>
                    <tr>
                    <td>Feminino</td>
                    <td><a href="http://localhost:7777/sexo/feminino">${feminino}</a></td>
                </tr>
                <tr>
                    <td>Masculino</td>
                    <td><a href="http://localhost:7777/sexo/masculino">${masculino}</a></td>
                </tr>
                <tr ">
                    <td>Outro</td>
                    <td><a href="http://localhost:7777/sexo/outro">${outro}</a></td>
                </tr>
                        `
                       

    return pagHTML
}

exports.distBySexo = function(lista, sexo ,data){
    
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de Pessoas (${sexo}) (${lista.length})</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`

    for(let i=0; i < lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                        <a href="http://localhost:7777/pessoas/${lista[i].id}">
                        ${lista[i].nome}
                        </a>
                           
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
        }
    

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}


exports.distribuicaoDesportoPage = function(lista, data){
    
    var pagHTML = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>Distribuição dos Desportos (${lista.length})</h1>
                </header>
                <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>
        
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>Desporto</th>
                        <th>Número</th>
                    </tr>`
                    
                        var dic={}
                        lista.forEach(pessoa => {
                            pessoa.desportos.forEach(desporto => {
                                if(desporto in dic){
                                    dic[desporto]+=1
                                }else{
                                    dic[desporto]=1
                                }
                            })
                          })

                        for (var desporto in dic){
                            pagHTML += `
                                    <tr>
                                        <td>${desporto}</td>
                            
                                        <td>
                                        <a href="http://localhost:7777/desporto/${desporto}">
                                            ${dic[desporto]}
                                        </a>    
                                        </td>
                                        
                                    </tr>
                            `
                            }
                       
                            pagHTML += `
                            </table>
                        </div>
                    
                        <footer class="w3-container w3-deep-purple">
                            <h5>Generated by pessoas-server: ${data}</h5>
                        </footer> 
                    </div>
                    </body>
                </html>
                    `                      
    return pagHTML
}


exports.distribuicaoDesportoPessoas= function(lista, desporto ,data){
    
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista do desporto (${desporto}) (${lista.length})</h1>
            </header>

            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>

        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`

    for(let i=0; i < lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                        <a href="http://localhost:7777/pessoas/${lista[i].id}">
                        ${lista[i].nome}
                        </a>
                           
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
        }
    

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}

exports.distribuicaoProfissaoPage = function(lista,data){
    var pagHTML =` 
    <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de top 10 profissoes</h1>
            </header>

            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>
                            <a 
                            href="http://localhost:7777/pessoas">
                            Lista de pessoas
                            </a>
                        </th>
                        <th>
                            <a 
                            href="http://localhost:7777/sexo">
                            Distribuição por sexo
                            </a>
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/desporto">
                            Distribuição por desporto
                            </a>
          
                        </th>
                        <th>
                        <a 
                            href="http://localhost:7777/profissoes">
                            Top 10 profissoes
                            </a>
                        
                        </th>
                    </tr>

                    <div class="w3-container">
                    <table class="w3-table-all">
                    <tr>
                        <th>Profissão</th>
                        <th>Número de profissionais</th>
                    </tr>
                `


    for(var i = 0 ; i<10; i++){
        
        pagHTML +=`
        <tr>
            <td>${lista[i][0]}</td>
            <td>
                <a href="/profissoes/${lista[i][0]}">${lista[i][1]}</a>
            </td>
        </tr>
        `
    }   



    pagHTML += `
    </table>
</div>

<footer class="w3-container w3-deep-purple">
    <h5>Generated by pessoas-server: ${data}</h5>
</footer> 
</div>
</body>
</html>
`
return pagHTML
}